### ISSUE TITLE
Make pre-commit hooks available in pylint-1.9.5

### ISSUE THREAD

**Issue by tomdodo** [PyCQA/pylint#3485]
The issue is about adding the `pre-commit-hooks.yaml` file to pylint-1.9.5 version. 
I know this issue has been fixed in pylint-2.4.0 and above. 
However, we have a repo in our system that is still on python2 and the highest pylint version that is python2 compatible is 1.9.5. 
Before you say 'you should migrate to python 3', this is exactly why we need this: pylint has the `pylint --py3k` option that will highlight any python2/3 compatibility problems in new code that is being committed, but this **must run on python 2** (otherwise it won't print out any errors, see https://github.com/PyCQA/pylint/issues/2956)

This is issue is about retroactively readding the `pre-commit-hooks.yaml` to version 1.9.5.

### Steps to reproduce
1. Use pre-commit hooks in a python project specifying python2 language and pylint-1.9.5 version
2. Configure a pre-commit hook such as 
```
- repo: https://github.com/PyCQA/pylint
    # latest py2 compatible version
    rev: pylint-1.9.5
    hooks:
      - id: pylint
        name: python2/3 compatibility
        language: python
        # need py2 for the py3 compatibility. If running on py3, check passes even with errors.
        language_version: python2
        args: [--py3k, -r=n, -f=parseable]
        types: [python]
```
3. The `git commit` fails with 
```
An error has occurred: InvalidManifestError:
=====> /Users/tommaso/.cache/pre-commit/repoayufqei0/.pre-commit-hooks.yaml does not exist
Check the log at /Users/tommaso/.cache/pre-commit/pre-commit.log
```

### Current behavior

Cannot use pylint-1.9.5 as a hook from another repo's `pre-commit-config.yaml`.

### Expected behavior

Should be able to use pylint-1.9.5 as a hook from another repo's `pre-commit-config.yaml`

### pylint --version output

N/A
