### ISSUE TITLE
Pylint crashes

### ISSUE THREAD

**Issue by ThatXliner** [PyCQA/pylint#4746]
I have 
```toml
[tool.pylint.MASTER]
load-plugins = "pylint_websockets"
```

With Pylint failing with

```
AttributeError: 'str' object has no attribute 'items'
```

_Originally posted by @ThatXliner in https://github.com/PyCQA/pylint/issues/3181#issuecomment-886100678_
