### ISSUE TITLE
Proper warning when the ``pyproject.toml`` options do not match existing options

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/pylint#5259]
### Current problem

We're not going to crash following the merging of #4720 but we need to define better what is expected in the pyproject.toml for pylint. When using:

```toml
[tool.pylint]
load-plugins = []
disable = "logging-not-lazy,logging-format-interpolation"
```
``load-plugins`` or ``disable`` are not valid options in the main namespace.

The expected configuration would be:

```toml
[tool.pylint]
    [tool.pylint."messages control"]
        disable = "logging-not-lazy,logging-format-interpolation"
    [tool.pylint."master"]
        load-plugins = []
```

But we're not warning the user about it.

### Desired solution

 We need to have proper error message when something is misplaced, because right now it's not very convenient. We're not going to crash following the merging of #4720 but we also should have an error message like:

``disable is not a valid section for pylint, did you mean '[tool.pylint."messages control"]  disable = ...' ?``

### Additional context

https://github.com/PyCQA/pylint/pull/4720#issuecomment-886204285
