### ISSUE TITLE
Docs request: how to enable all optional checkers

### ISSUE THREAD

**Issue by jamesbraza** [PyCQA/pylint#8204]
### Question

From https://pylint.readthedocs.io/en/latest/user_guide/checkers/extensions.html#optional-checkers

> You can activate any or all of these extensions by adding a `load-plugins` line to the MAIN section of your `.pylintrc`

Is there a way to load all of them?  I configure `pylint` using `pyproject.toml` and am wondering if this loads all of them:

```toml
[tool.pylint.master]

# List of plugins (as comma separated values of python module names) to load,
# usually to register additional checkers.
load-plugins = []
```

### Documentation for future user

I expect it to be in the same place: https://pylint.readthedocs.io/en/latest/user_guide/checkers/extensions.html#optional-checkers

### Additional context

With [`ruff`](https://github.com/charliermarsh/ruff) you can pass their [equivalent parameter `select` the string `"ALL"`](https://github.com/charliermarsh/ruff#command-line-interface) to accomplish this.

**Comment by DanielNoord** [comment]
This is related to https://github.com/PyCQA/pylint/issues/6938 as that is the reason this doesn't show.
You can get this behaviour with `pylint --load-all-extensions=y       `

**Comment by jamesbraza** [comment]
```toml
[tool.pylint.master]

load-all-extensions = "y"
```

Running `pylint` now gives `E0015: Unrecognized option found: load-all-extensions (unrecognized-option)`

@DanielNoord are you sure that works?

I see `enable-all-extensions` commented in the [example pylintrc](https://github.com/PyCQA/pylint/blob/main/examples/pylintrc#L14), might that work?
