### ISSUE TITLE
pyproject.toml needs enable-all-extensions

### ISSUE THREAD

**Issue by jamesbraza** [PyCQA/pylint#8217]
### Bug description

A command line call `pylint --enable-all-extensions package` works, now to place it into my `pyproject.toml` config.

The example [`pylintrc`](https://github.com/PyCQA/pylint/blob/v2.16.1/examples/pylintrc) has [`enable-all-extensions`](https://github.com/PyCQA/pylint/blob/v2.16.1/examples/pylintrc#L14) which can be used to enable all extensions.

Unfortunately, this key doesn't exist in the example [`pyproject.toml`](https://github.com/PyCQA/pylint/blob/v2.16.1/examples/pyproject.toml).  Also, it doesn't seem to work:

```toml
[tool.pylint.master]

# None of these are working
enable-all-extensions = true
enable-all-extensions = "y"
enable-all-extensions = {}
enable-all-extensions = []
enable-all-extensions = ["y"]
```

### Command used

```shell
n/a
```

### Pylint output

```shell
n/a
```

### Expected behavior

I would like if `pyproject.toml` configs have parity with command line args.

Bonus points if this `enable-all-extensions` gets documented here: https://pylint.readthedocs.io/en/latest/user_guide/checkers/extensions.html#optional-checkers

### Pylint version

```shell
pylint 2.16.1
astroid 2.14.1
Python 3.10.9 (main, Jan  6 2023, 11:19:20) [Clang 14.0.0 (clang-1400.0.29.102)]
```

### OS / Environment

macOS Monterey version 12.6
